ekf_filter_node:
    ros__parameters:
      frequency: 50.0
      two_d_mode: false
      publish_acceleration: false
      publish_tf: true

      map_frame: map
      odom_frame: odom
      base_link_frame: base_footprint
      world_frame: odom

      odom0: base_controller/odom
      odom0_config: [ false, false, false,
                      false, false, false,
                      true,  true,  true,
                      false, false, true,
                      false, false, false]
      odom0_differential: false

      imu0: imu_raw
      imu0_config: [false, false, false,
                    true,  true,  false,
                    false, false, false,
                    true,  true,  true,
                    false, false, false]
      imu0_differential: false